-- The ingest ledger. One row per episode this service has ever attempted to post.
CREATE TABLE ingested_episode
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    episode_key            VARCHAR(512)  NOT NULL,
    episode_name           VARCHAR(1024) NOT NULL,
    group_id               VARCHAR(128)  NOT NULL,
    status                 VARCHAR(32)   NOT NULL,
    attempts               INTEGER       NOT NULL DEFAULT 0,
    occurred_at            TIMESTAMP WITH TIME ZONE NOT NULL,
    posted_at              TIMESTAMP WITH TIME ZONE,
    verified_at            TIMESTAMP WITH TIME ZONE,
    last_error             VARCHAR(2048),
    created_date_time      TIMESTAMP WITH TIME ZONE NOT NULL,
    last_modified_date_time TIMESTAMP WITH TIME ZONE NOT NULL
);

-- The idempotency guarantee. Without this, a concurrent or repeated run could post the
-- same activity twice and there would be no way to tell the duplicates apart afterwards.
CREATE UNIQUE INDEX ux_ingested_episode_key ON ingested_episode (episode_key);

-- Supports the per-run "what still needs work" scan.
CREATE INDEX ix_ingested_episode_status ON ingested_episode (status, occurred_at);
